name_prefix: sim # run-minitrace
benchmarks: 
  - crisp-artifact:render_passes_2k
  - crisp-artifact:render_passes_2k_lod0
  - pipeline:minitrace

instances:
  - ORIN_1
  - ORIN_2
  - ORIN_3

launcher: idun

override_names: true

experiment:
  path: $ACCEL_SIM/pipeline/setup/experiments.yaml
  name: more_streaming_multiprocessors

extra_configs:
  - SASS
  - concurrent
  - fg
  - VISUAL

aggregate: true

#Options for collect
collect:
  logfiles: /cluster/home/jorgfi/crisp_results/logfiles
  detailed: true
  metric: gpu_tot_ipc

trace_lookup: $ACCEL_SIM/pipeline/setup/traces.yaml
results_dir: /cluster/home/jorgfi/crisp_results
#results_dir: $ACCEL_SIM/pipeline/results

config_destinations:
  gpgpusim: $ACCEL_SIM/gpu-simulator/gpgpu-sim/configs/custom-cfgs
  trace: $ACCEL_SIM/gpu-simulator/configs/custom-cfgs

# For Slurm jobs. 
# See more configuration-options in accel-sim-framework/util/job_launching/idun.yaml.
job_mem: 16G # Default is 4G, but this turned out to be insufficient for the workloads in the artifact.