name_prefix: run-20240723-1728 # run-minitrace
benchmark: crisp-artifact:render_passes_2k # pipeline:minitrace
instances:
  - ORIN
  - RTX3070
launcher: idun
extra_configs:
  - SASS
  - concurrent
  - fg
  - VISUAL
aggregate: true
trace_dir: $ACCEL_SIM/hw_run/traces/vulkan/ # $ACCEL_SIM/pipeline/traces/
results_dir: $ACCEL_SIM/pipeline/results
config_destinations:
  gpgpusim: $ACCEL_SIM/gpu-simulator/gpgpu-sim/configs/custom-cfgs
  trace: $ACCEL_SIM/gpu-simulator/configs/custom-cfgs
